mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from restaurant_menu import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('restaurant_menu.urls')),
    # Example of not using include, I simply hardcoded, that for this project, homepage will be views.MenuListView.as_view()
    # If I had path('whatever', include('restaurant_menu.urls')), urls from app restaurant menu would look like localhost/whatever/about itd
    # This would be ok if I had one app.
    # path('', views.MenuListView.as_view(), name='home')

]

restaurant_menu/urls.py
from django.urls import path
from . import views

# We can add urls for this app here, and then include them inside project urls, or hardcode these urls in project urls

urlpatterns = [
    # First argument -> url, Second argument -> function or class to be triggered when user enters the url,
    # as_view -> it renders the class as actual view. Nie potrzebujemy tego w function-based views, tam używamy funkcji render() wewnątrz funkcji
    path('', views.MenuListView.as_view(), name='home'),
    path('item/<int:pk>/', views.MenuItemDetail.as_view(), name='menu_item'),
    path('about/', views.AboutView.as_view(), name='about'),
]

restaurant_menu/models.py
from django.db import models
from django.contrib.auth.models import User

# If author is deleted, models.CASCADE will delete all the meals that this author had created.
# models.PROTECT -> I won't be able to delete a User.
# models.SET_NULL -> The user will be deleted, and it will be set to NULL on the item instances.


MEAL_TYPE = (
    ('starters', 'Starters'),
    ('salads', 'Salads'),
    ('main_dishes', 'Main Dishes'),
    ('desserts', 'Desserts')
)

STATUS = (
    (0, 'Unavailable'),
    (1, 'Available'),
)


class Item(models.Model):
    meal = models.CharField(max_length=1000, unique=True)
    description = models.CharField(max_length=2000)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    meal_type = models.CharField(max_length=200, choices=MEAL_TYPE)
    author = models.ForeignKey(User, on_delete=models.PROTECT)
    status = models.IntegerField(choices=STATUS, default=0)
    date_created = models.DateTimeField(auto_now_add=True)  # auto_now_add -> Automatically set the field to now when the object is first created.
    date_updated = models.DateTimeField(auto_now=True)  # auto_now -> Automatically set the field to now every time the object is saved.

    def __str__(self):
        return self.meal

restaurant_menu/views.py
from django.shortcuts import render
from django.views import generic
from .models import Item, MEAL_TYPE


# To retrieve objects from your database, construct a QuerySet via a Manager on your model class.
# A QuerySet represents a collection of objects from your database. It can have zero, one or many filters.
# Filters narrow down the query results based on the given parameters. In SQL terms, a QuerySet equates to a SELECT statement, and a filter is a limiting clause such as WHERE or LIMIT.
# You get a QuerySet by using your model’s Manager. Each model has at least one Manager, and it’s called objects by default.


class MenuListView(generic.ListView):
    # queryset wil store the list of data to display. We are basically querying the data from database table. All the objects from DB we want to display
    queryset = Item.objects.order_by("date_created")
    template_name = 'index.html'

    # AFAIU context are variables we want to display on the view, like render(req, template, dict_context)
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['meal_types'] = MEAL_TYPE
        return context


class MenuItemDetail(generic.DetailView):
    model = Item
    template_name = 'menu_item_detail.html'


class AboutView(generic.TemplateView):
    template_name = 'about.html'

restaurant_menu/templates/about.html
{% extends 'base.html' %}
{% block content %}
<h2>This app was created while learning Django framework</h2>
{% endblock content %}

restaurant_menu/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor"
          crossorigin="anonymous">
    
    <title>Menu Products</title>
</head>
<body>
    <nav class="navbar navbar-expand-lg bg-light">
        <div class="container-fluid">
            <a class="navbar-brand" href="#"></a>
            
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'home' %}">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" aria-current="page" href="{% url 'about' %}">About</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    
    {% block content %}
    {% endblock content %}
    
    <!-- JavaScript Bundle with Popper -->
    <script src="https://code.jquery.com/jquery-2.1.3.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2"
            crossorigin="anonymous"></script>

</body>
</html>

restaurant_menu/templates/index.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
    <h1>Restaurant Menu</h1>
    <ul class="list-group list-group-flash">
        {% for meal_type in meal_types %}
        <h2 class="pt-5">{{ meal_type.1 }}</h2>
        {% for meal in item_list %}
        {% if meal.meal_type == meal_type.0 %}
        
        {% if not meal.status %}
        <li class="list-group-item d-flex justify-content-between align-items-center border-0 pb-0">
            <a href="{% url 'menu_item' meal.pk %}">
                <h3>
                    <del>{{ meal.meal }}</del>
                </h3>
            </a>
            <span class="badge bg-primary rounded-pill">{{ meal.price }} $</span>
        </li>
        <li class="list-group-item pt-0">
            <p>{{ meal.description }}</p>
        </li>
        
        {% else %}
        
        <li class="list-group-item d-flex justify-content-between align-items-center border-0 pb-0">
            <a href="{% url 'menu_item' meal.pk %}"><h3>{{ meal.meal }}</h3></a>
            <span class="badge bg-primary rounded-pill">{{ meal.price }} $</span>
        </li>
        <li class="list-group-item pt-0">
            <p>{{ meal.description }}</p>
        </li>
        
        {% endif %}
        {% endif %}
        {% endfor %}
        {% endfor %}
    </ul>
</div>

{% endblock content %}

restaurant_menu/templates/menu_item_detail.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
    <h1>{{ item.meal }}</h1>
    <p><b>Ingredients:</b> {{ item.description }}</p>
    <p><b>Price:</b> {{ item.price }} $</p>
</div>
{% endblock content %}